print("\033[33m=== Simulador de Aventura ===\033[0m")
print()
print("Bem-vindo bravo aventureiro!")
print()
print("Você vai responder a algumas perguntas e então vamos criar uma história incrível com \033[36mVOCÊ\033[0m como o protagonista! 🤩")
print()
name = input("Seu nome: ")
enemy = input("Nome do seu pior inimigo: ")
super_power = input("Seu super poder: ")
print()
print("Nossa história começa quando nosso herói,\033[34m", name, "\033[0mse aproxima de um \033[30mcastelo ameaçador...\033[0m")
print("De repente, um raio atinge o chão aos pés de,\033[34m", name, "\033[0m")
print("\033[31m'NOSSA BATALHA FINAL COMEÇA!'\033[0m grita o malvado\033[35m", enemy, "\033[0mclaramente sem perceber que\033[34m", name, "\033[0mtem o poder do\033[32m", super_power, "\033[0mo que significa que ele vencerá com bastante facilidade.")