name_food = input("Nome de uma comida >> ")
name_plant = input("Nome de uma planta >> ")
name_cooking = input("Nome de um método de cozimento >> ")
describe_burned_food = input("Com que palavra descreveria comida queimada? >> ")
name_item = input("Nome de uma ferramenta >> ")
furniture_item = input("Nome de um móvel da casa >> ")
print()
print("MENU")
print(name_cooking, name_food, "com", name_plant, describe_burned_food, "em um(a)", furniture_item, "de", name_item)