name_food = input("Name a food >> ")
name_plant = input("Name a type of plant >> ")
name_cooking = input("Name a method of cooking >> ")
describe_burned_food = input("What word describes burned food? >> ")
name_item = input("Name a DIY item >> ")
print()
print("MENU")
print(name_cooking, name_food, "with", describe_burned_food, name_plant, "on a bed of", name_item)