print("Vamos conhecer você!")
print()
my_name = input("Qual o seu nome? ")
my_favorite_food = input("Qual a sua comida favorita? ")
my_favorite_music = input("Qual a sua música favorita? ")
my_state = input("Onde você mora? ")
print()
print("Você é")
print(my_name)
print("Você provavelmente está com fome de")
print(my_favorite_food)
print("e você definitivamente deve está curtindo o ritmo de")
print(my_favorite_music)
print("morando na incrível")
print(my_state)