print("Getting to know you!")
print()
my_name = input("What's your name? ")
my_favorite_food = input("What's your favorite food? ")
my_favorite_music = input("What's your favorite music? ")
my_state = input("Where do you live? ")
print()
print("You are")
print(my_name)
print("You're prabably hungry for")
print(my_favorite_food)
print("and you're definitely getting your groove on to")
print(my_favorite_music)
print("living in the amazing")
print(my_state)